# Generated by Django 3.1.7 on 2021-04-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
