# Generated by Django 3.1.7 on 2021-04-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210416_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasks',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usertasks',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
