# Generated by Django 3.1.7 on 2021-04-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210416_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertasks',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='usertasks',
            name='start_time',
        ),
        migrations.AddField(
            model_name='usertasks',
            name='end',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='usertasks',
            name='start',
            field=models.TimeField(default=None),
        ),
    ]
