# Generated by Django 3.1.7 on 2021-04-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210416_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasks',
            name='project',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
