# Generated by Django 3.1.7 on 2021-04-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210416_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasks',
            name='project',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
