# Generated by Django 3.1.7 on 2021-04-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_usertasks_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasks',
            name='duration',
            field=models.DurationField(blank=True, default=None),
        ),
    ]
