# Generated by Django 3.1.7 on 2021-04-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210416_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasks',
            name='duration',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
